# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f85791478c44e5f1264c6bfa2e4ac90b83a07c0901130f6a4830612261c391e227fd6df3709ba71cccec9b7344e39bab7d58818747c792259499cbb8e56f25

test:
  secret_key_base: dc611f4251369a2c483236dec7c12f04b4bab029378b10ef43c3d9c1d8448196f992a0e92d22d4665fa1295c29e09fb0ec007a5e13ba86a7788b6143ff84ac72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
